### ISSUE TITLE
Remove large unnecessary files from version control

### ISSUE THREAD

**Issue by dwcaraway** [opticks-org/opticks#4]
I noticed some larger files in the repo. Can any of them be moved to other storage locations or to a Github release? 

```bash
$ du -cksh *
/* Output is
 27M	Code
3.5M	Dependencies
 12K	HelperScripts
 46M	Release
 77M	total
*/
```

Particularly, it looks like the Release folder might contain large static files. These files can be added back in when building releases by a CI system but otherwise stored elsewhere to speed up repo cloning.

```bash
$ du -h **/*.zip
/* Output is
4.0K	Code/application/dummyjvm.zip
 21M	Release/Help/Opticks-Src.zip
 21M	Release/Help/Opticks.zip
*/
```

**Comment by tclarke** [comment]
These are not available elsewhere and are meant to be revision controlled so I'm going to keep them here for the time being. The dummyjvm hasn't been used by any plugins afaik for some time so it could be removed but requires some code changes (I'll look into removal). The help files should stay until the manual has been moved away from Robohelp.

**Comment by dwcaraway** [comment]
Are the files in version control changing and are not built via automated tools? If so, version control is the right spot. Otherwise, it would be better to host statically somewhere (Github, AWS, some web accessible location that can support `wget`) and just pull them in during builds.

**Comment by tclarke** [comment]
They are not automatically built. They use a tool called Robohelp with is a per-seat licensed tool and is a gui tool (manual build). When docs change they need to be rebuilt and checked in. I'm trying to remove the reliance on Robohelp per the docs issue.
