### ISSUE TITLE
Update developer docs

### ISSUE THREAD

**Issue by bradh** [opticks-org/opticks#453]
**Is your feature request related to a problem? Please describe.**
When looking for the development guide, the instructions at https://www.opticks.org/display/opticksDev appear outdated.

**Describe the solution you'd like**
Updated build guide (ideally for Linux).

**Describe alternatives you've considered**
Remove page and just put into the README.

**Additional context**
Nil at this time.

**Comment by tclarke** [comment]
You can look at the SDK tutorials for a lot of the information. We're currently changing the build system to use cmake which will ease a lot of the build issues.
