### ISSUE TITLE
deb release

### ISSUE THREAD

**Issue by RaananHadar** [opticks-org/opticks#456]
**Is your feature request related to a problem? Please describe.**
I want to run opticks on ubuntu, I tried and unfortunately failed to build it from source.

**Describe the solution you'd like**
A debian/ubuntu package is desirable as it is a relatively popular linux distro.

**Comment by tclarke** [comment]
I'm not sure if I'll be able to regularly build a deb unless I can find a useful multi-distro packaging system. We'd accept deb builds if someone wants to make them. Also, to install from the default apt sources, the packages are generated by the distro I believe so more research would be needed for that.

**Comment by RaananHadar** [comment]
if that is the case, I guess snap is a good alternative.

**Comment by tclarke** [comment]
I'm going to put this issue on hold for the time being. We're currently working a few issues that will make building and packaging much easier. The biggest one of not for linux is the cmake branch. You can try building that now and you might get something workable. It will make it possible to use system installed libs for most of the third party dependencies and standardize the build process on different platforms. When that is finished you may be able to build on your system with no issues. At that point I can look into getting Opticks into the official repos if I can find a volunteer more familiar with deb to help with the package config files.

**Comment by RaananHadar** [comment]
thank you.
