### ISSUE TITLE
The opticks.org website has disappeared

### ISSUE THREAD

**Issue by jratike80** [opticks-org/opticks#466]
The website https://opticks.org does not seem to exist. I wonder if it means that the whole Opticks project is inactive.

**Comment by jratike80** [comment]
I just would have liked to add a link to opticks when I as writing an answer to a question at gis.stackexchange. However, the most part of the documentation seems to be in the non-accessible opticks.org site. Even https://github.com/opticks-org/opticks points users to search documentation from there.

**Comment by tclarke** [comment]
I've created a new issue to move the website to github pages. I'm putting up a basic page now but it will need to be expanded. See #467

**Comment by AmazingSAR** [comment]
Has anyone download https://opticks.org/downloads/working_deps/raptor-1.4.16-windows-mods.zip file?

**Comment by tclarke** [comment]
Transferred this issue to [opticks-org/www](https://github.com/opticks-org/www/issues/1)
