### ISSUE TITLE
Documentation Format?

### ISSUE THREAD

**Issue by dwcaraway** [opticks-org/opticks#7]
I usually build documentation in [ReadTheDocs](https://readthedocs.org/ ) style formats, thoughts? and [an example set of documentation for a mixed python / c++ library using SCons](http://docs.godotengine.org/)

**Comment by tclarke** [comment]
I was thinking wither ReadTheDocs, doxygen static files (only because the API docs are in doxygen) or a ssg tool like Jekyll or Hugo.

**Comment by dwcaraway** [comment]
ReadTheDocs (e.g. `sphinx`) will give you all of the support for compiling to HTML/CSS/JS, support restructured text  and producing PDFs and other formats for offsite hosting. I use Jekyll for CMS, Github pages and blogging (along with other web-based databases to provide content), but generally don't find a lot of value for docs. Haven't used Hugo, expecting it to be similar. I've used doxygen in the past, worked well for generated docs from source code.

Here's a post on using [rtd/sphinx to publish to github pages](https://daler.github.io/sphinxdoc-test/includeme.html). Optionally, you can post to ReadTheDocs with themes.
